import type { Metadata } from "next";
import { inter } from '@/app/ui/fonts';
import "./globals.css";
import { Navbar } from "@/components/ui/navbar";
import { SessionProvider } from "@/components/sessionProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Footer from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions as any);

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-white`}>
        <SessionProvider session={session}>
          <Navbar />  
          {children}
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  );
}
