name: Deploy

on:
  push:
    branches:
      - main

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Set up production env file
      run: |
        echo "${{secrets.PRODUCTION_ENV_FILE}}" > .env.production

    - name: Login into docker
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}


    - name: Set up Docker Build and Push
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags:
          maxdev123/slack_reserver:site_latest
        build-args: |
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}

  deploy:
    needs: image-push
    runs-on: ubuntu-latest
    steps:
    - name: Zero Downtime Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd app
          docker compose pull
          docker rollout slack_site
          